project_id = "ahfbgstenyxmxxjjpjiw"

[functions.get-sol-balance]
verify_jwt = false

[functions.process-payout]
verify_jwt = false

[functions.detect-stake-transaction]
verify_jwt = false

[functions.generate-mix-wallet]
verify_jwt = false

[functions.detect-mix-transaction]
verify_jwt = false

[functions.process-mix]
verify_jwt = false
